name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
filter-by-commitish: true
categories:
  - title: "✨ Features"
    labels:
      - "feature"
  - title: "⚡ Enhancement"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "📝 Documentation"
    labels:
      - "documentation"
  - title: "🆙 Dependencies Update"
    labels:
      - "dependencies"
change-title-escapes: '\<*_&'
exclude-labels:
  - "exclude from changelog"
template: |
  ## Changes
  <!-- ここに主要な変更点をまとめる -->
  $CHANGES