name: Deploy to production

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:

  
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - name: Generate tag
        id: image_tag
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M')
          echo "VERSION=v$VERSION" >> $GITHUB_OUTPUT
        env:
          TZ: 'Asia/Tokyo'

      - name: Echo tag
        id: echo
        run: |
          echo hi